### PR TITLE
Add groupEmit and userSockets Methods

### PR DESCRIPTION
**Pull request by jcbantuelle**
Thank you for creating this package, it's been incredibly helpful for me!

When using it in my app, I ran into a couple of use cases that I thought might be helpful additions back to the package for others. This PR adds two new methods:

`userSockets` - Retrieve a list of sockets, looked up by passing in a list of userIds.

`groupEmit` - Send a message to a list of sockets. It's similar to `broadcast`, but instead of providing an exclusion blacklist, it takes an inclusion whitelist.

Please let me know what you think, and if there's any issues you'd like me to address.

### CODE REVIEW

**Comment by YuukanOO** [comment]
Hi, thanks for contributing!

Some thoughts. For ease of use may be we should just implements `userSockets` using the existing `Streamy.sockets` method by checking if the given parameter is an array.

And if the `Streamy.sockets` returns an object with an `emit`method, the `groupEmit` is not needed anymore.

**Comment by jcbantuelle** [comment]
Thanks for the feedback! I've implemented the changes you suggested, and the api is much simpler for it. Please let me know if you have concerns about how I coded any of it up.

**Comment by YuukanOO** [comment]
Whoops, didn't see you want to pass an array of **user ids** and not **session ids**, my bad!

So, new thoughts. In `lib/core_server.js`, the `to` parameter is used to send the message via the `send` method. We just need to create a function that returns an object with a send method which loop through each sockets and call the appropriate `send`. Something like this:

```javascript
Streamy.socketsForUsers = function(uid or array of uids) {
  // (...) Code to retrieve associated sockets

  return {
    send: function(data) {
      _.each(sockets, function() { this.send(data); });
    }
  };
}
```

We must also implements `Streamy.sockets` so that it also accepts an array of session ids.

Again, sorry for pointing you in the wrong direction.

**Comment by jcbantuelle** [comment]
haha, no worries. I've pulled the behavior out of the `sockets` method and into a new method named `sessionsForUsers` to keep in line with what you proposed. I went in a slightly different direction based on my use case, but tried to follow the pattern of your sample code. This approach meant I didn't need to touch any of the existing method code. Hopefully it checks out, but if you have any concerns please let me know.

**Comment by YuukanOO** [comment]
Ok, so i'll had to add `socketsForUsers` too :) Did you test it from the client too?

**Comment by jcbantuelle** [comment]
I was thinking this would be a server-only method because it depends on `Streamy.sockets` to do a filter on the userId. I may have misunderstood something though, so if you think there's a way to expand this to the client-side as well I don't mind making that change.

**Comment by YuukanOO** [comment]
`Streamy.sessions` is also used by the client for direct messages but it should work without any modifications, we just need to test it.

**Comment by jcbantuelle** [comment]
My apologies, I think I must be misunderstanding something. The `sessionsForUsers` method I wrote is currently in the `core_server.js` file. This file is only loaded by the server, so on the client it throws an undefined method error. I could move it into the `direct_messages.js` file so that the client loads it as well, but when it's there you still receive the following error: `Streamy.sockets is not a function` because the method I wrote needs to filter on `userId` which is only captured in the sessions object on the server-side.

**Comment by YuukanOO** [comment]
You may want to test my latest commit 6de9e92c656e8e2ad3187464b04441f7dc656608

**Comment by jcbantuelle** [comment]
Ahhh, I understand much better now what you were suggesting. Thanks for all your help! I'll pull this work into my project and test it out.

**Comment by YuukanOO** [comment]
@jcbantuelle So... Any bugs?

**Comment by jcbantuelle** [comment]
@YuukanOO Sorry for the delay! I just tested it out and noticed a small snag. I've opened a PR to address it at https://github.com/YuukanOO/streamy/pull/19.

**Pull request merged**
