### PR TITLE
Multiple servers support

### PR DESCRIPTION
**Pull request by nlhuykhang**
The current API is updated to bring in multiple servers support, but it will still work with older versions of Streamy. Following functions is updated:

- `Streamy.on(message_name, callback, [ddp_connection])`
- `Streamy.emit(message_name, data_object, [socket/ddp_connection])`
- `Streamy.off(message_name, [ddp_connection])`
- `Streamy.onConnect(callback, [ddp_connection])`
- `Streamy.onDisconnect(callback, [ddp_connection])`

New functions:

- `Streamy.initConnection(ddp_connection)`
- `Streamy.clearConnection(ddp_connection)`

Rated issue: #30

### CODE REVIEW

**Comment by nlhuykhang** [comment]
@YuukanOO Could you have a look at this PR?

**Comment by nlhuykhang** [comment]
@YuukanOO not sure if you missed this PR, please have a look and let me know if there is any possible issue

**Comment by YuukanOO** [comment]
@nlhuykhang Didn't miss it but did not have the time sooner, sorry.

So, I've been thinking about how to do it and I think we need to break things this time.

Basically, here is what I think could be a better approach.

Make `Streamy` a class. In its constructor, pass in an host url. If no host is provided, use the meteor default ddp connection.

Then every functions such as `emit`, `on`, `broadcast`, `...` should now be a method on the `Streamy` class. When you want to use Streamy, just instantiate a `new Streamy(host_url)` and keep a reference to it.

What do you think?

**Comment by nlhuykhang** [comment]
That a good approach @YuukanOO , but doing that we will have to convert the entire source code to ES6. I know that is a good thing to do but I would take a lot of time and will for sure break older code. 
In fact, I thought about that before working on this PR and decided to keep the current API and work on it first, we can convert to ES6 later and release it as the v2 version. This way is much faster, in addition v1 version will have multiple servers support so projects using pre-1.3 Meteor version are still be able to use it.

**Comment by YuukanOO** [comment]
No need for ES6, just use ES5 for now to keep things simple. Add methods to the `prototype` and everything will be good. Multiple server support needs to be done right to keep the library simple to use.

**Comment by nlhuykhang** [comment]
Ok sound good, I will work on updating this PR. Could you give me some suggestion on how the API should look like?

**Comment by YuukanOO** [comment]
The API should be the same expect that it is tied to an instance of `Streamy`. Something like that:

```javascript
function Streamy(host) { /* ... */ }
Streamy.prototype.on = function() { /* ... */ }
Streamy.prototype.off = function() { /* ... */ }
Streamy.prototype.emit = function() { /* ... */ }

// Usage
var con = new Streamy();
con.on('ping', function() { console.log('pong'); });
con.close();
```

**Comment by nlhuykhang** [comment]
hey @YuukanOO , I just updated this PR. What do you think?

**Comment by nlhuykhang** [comment]
@YuukanOO , I know you are busy, but could you have a look?

**Comment by nlhuykhang** [comment]
@YuukanOO please publish the new version to Atmosphere, I can not use the new functions, e.g. `.off`, `.close` 😞

**Comment by YuukanOO** [comment]
Hmm, I think we must break the compatibility this time so the `Connection` "class" does not make sense to me. `Streamy` should become a constructor.

**Comment by nlhuykhang** [comment]
Are you sure? there are many projects depending on this package (mine too), and I know that many of them do not specify a version explicitly. Doing that could break many things, please think about that again, we could try using another name instead of `Connection`. Do you have any suggestions?

**Comment by YuukanOO** [comment]
Ok for now, i'll merge it as it is. But keep in mind that version 2 (if I managed to release it) will break thnigs.

**Pull request merged**
