### PR TITLE
Configurable DDP connection and server

### PR DESCRIPTION
**Pull request by dj-foxxy**
Make the DDP connection (on the client) and DDP server (on the server) configurable. For example, the user sets the connection by;

```JavaScript
// Client - before startup callbacks are called.
var connection = DDP.connect('http://localhost:3000');
Streamy.setInitOptions({connection: connection});
```

If the user doesn't set the connection or server, the defaults are used (as before).

Initially, I was going to remove the `Meteor.startup` that calls `Streamy.init` and call it manually with options but I wanted to preserve the current behaviour. However, if the user calls `Streamy.setInitOptions()` after `Streamy.init()` the error is silently ignored.

The pull request looks a lot more scary than it really is: most of it is examples.

Thanks for creating Streamy.

### CODE REVIEW

**Comment by YuukanOO** [comment]
Hi, thanks your work!

Maybe we should just keep `Streamy.init(options)` and remove the `setInitOptions` method to keep it simple and short. Perhaps using the same option property for client and server (instead of **connection** and **server**), something like **endpoint** or else.

If we remove the `setInitOptions`, we should remove the startup method and explain in the README to call it explicitly with or without the `options` parameter.

I know you want to preserve the initial behaviour but I'm not afraid of making breaking changes for good reasons :)

Let me know what you think!

**Comment by dj-foxxy** [comment]
Hi. Sorry, I haven't got back in a while. I'm going to close this pull request because of bugs with Streamy.id() and some other things that use Meteor.(server|connection). I'll pick this up in a few weeks. Thanks.

**Comment by dj-foxxy** [comment]
Hi @YuukanOO, 

I've picked this up again. Basically the code has become embedded in a larger project but I back-ported it my fork.

All the code has been scooped into a class hierarchy ([share](https://github.com/foxdog-studios/streamy/blob/master/lib/core/impl_base.js), [client](https://github.com/foxdog-studios/streamy/blob/master/lib/core/impl_client.js), [server](https://github.com/foxdog-studios/streamy/blob/master/lib/core/impl_server.js)).

[The user can `new` as many Streamy instances with different connections](https://github.com/foxdog-studios/streamy/blob/master/lib/core/impl_instance.js). I've made the library work by binding instance methods to the current API ([shared](https://github.com/foxdog-studios/streamy/blob/master/lib/core/impl_server.js), [client](https://github.com/foxdog-studios/streamy/blob/master/lib/core/core_client.js), [server](https://github.com/foxdog-studios/streamy/blob/master/lib/core/core_client.js)).

Obviously, I'm not asking for this code to be merged, just though I'd share my progress.

Thanks,


Peter.

**Comment by YuukanOO** [comment]
Hey @dj-foxxy ! Glad you reported back :)

I'm planning a new major version for Streamy and I will try to make it work for multiple connections.

**Comment by dj-foxxy** [comment]
Cool,  I post my code on another branch. It's probably not that useful because we're not using Meteor users, broadcast, or direct message so it's got a lot less features.

**Pull request closed without merging**
